default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: blog_application_development

test:
  <<: *default
  database: blog_application_test

production:
  <<: *default
  database: blog_application_production
  username: blog_application
  password: <%= ENV["BLOG_APPLICATION_DATABASE_PASSWORD"] %>
